version: "3.8"

services:
  next:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/next
    networks:
      - docker_net
    depends_on:
      - postgres
    entrypoint: /usr/next/entrypoint-dev.sh
  postgres:
    image: postgres:latest
    # you can use postgres.docker_net as the hostname internally
    hostname: postgres
    networks:
      - docker_net
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: docker_crud
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - ./app/.env
    ports:
      - 5555:5555

networks:
  docker_net:
    name: docker_net
volumes:
  postgres-data:
  pg-admin-data:
