version: "3.8"

services:
  next:
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    ports:
      - 3002:3002
      # 5555 is for Prisma Studio
      - 5555:5555
    volumes:
      - ./app:/usr/next
    networks:
      - docker_net
    depends_on:
      - postgres
    entrypoint: /usr/next/entrypoint-dev.sh
  postgres:
    image: postgres:latest
    # you can use postgres.docker_net as the hostname internally
    hostname: postgres
    networks:
      - docker_net
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: docker_crud
    env_file:
      - ./.env.development
    ports:
      - 5432:5432
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    networks:
      - docker_net
    ports:
      - "5050:5050"
    volumes:
      - pg-admin-data:/var/lib/pgadmin

networks:
  docker_net:
    name: docker_net
volumes:
  postgres-data:
  pg-admin-data:
