version: "3.8"

services:
  db:
    image: postgres:latest
    networks:
      - docker_net
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.devcontainer/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_crud
    env_file:
      - ./server/.env.development
    ports:
      - 5432:5432
networks:
  docker_net:
    name: docker_net

volumes:
  postgres-data: